[package]
name = "redcoat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
chrono = "0.4"
flate2 = "1.0.20"
reqwest = "0.11.3"
tokio = { version = "1", features = ["full"] }